"""empty message

Revision ID: 1c70c4402f76
Revises: d47ba657b984
Create Date: 2020-10-27 10:54:18.473729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c70c4402f76'
down_revision = 'd47ba657b984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('populated', sa.BOOLEAN(), nullable=True))
    op.execute("UPDATE companies SET populated = false")
    op.alter_column('companies', 'populated', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'populated')
    # ### end Alembic commands ###
