"""empty message

Revision ID: 306e75e0f0c4
Revises: b38fe4612cee
Create Date: 2020-10-27 10:41:45.781845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306e75e0f0c4'
down_revision = 'b38fe4612cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_opened', sa.Float(), nullable=True),
    sa.Column('price_closed', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    # ### end Alembic commands ###
