"""empty message

Revision ID: 506fae711ef9
Revises: 1c70c4402f76
Create Date: 2020-10-27 12:45:57.757973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506fae711ef9'
down_revision = '1c70c4402f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_company_privileges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('quotes_date_key', 'quotes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('quotes_date_key', 'quotes', ['date'])
    op.drop_table('user_company_privileges')
    # ### end Alembic commands ###
